name: Dispatch README

on:
  repository_dispatch:
    types:
      - dispatch_readme

jobs:
  generate:
    name: Generate README
    permissions:
      contents: write
    uses: Gakuto1112/FiguraAvatarsReadmeTemplate/.github/workflows/generate_my_figura_avatar_readme.yml@main
    with:
      branch-name: main